require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '9.0'

target 'CredMaker' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  target 'CredMakerTests' do
    inherit! :complete
    # Pods for testing
  end

end

target 'CredMaker-tvOS' do
  # Pods for CredMaker-tvOS

  target 'CredMaker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# TODO: add this back to clean up build warnings
#post_install do |pi|
#    pi.pods_project.targets.each do |t|
#        t.build_configurations.each do |config|
#            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
#        end
#    end
#end